export const ENV_KEYS = {
  DB_HOST: "DB_HOST",
  DB_PORT: "DB_PORT",
  DB_USERNAME: "DB_USERNAME",
  DB_PASSWORD: "DB_PASSWORD",
  DB_NAME: "DB_NAME",
  DB_SYNCHRONIZE: "DB_SYNCHRONIZE",
  JWT_SECRET: "JWT_SECRET",
  JWT_REFRESH_SECRET: "JWT_REFRESH_SECRET",
  JWT_TOKEN_AUDIENCE: "JWT_TOKEN_AUDIENCE",
  JWT_TOKEN_ISSUE: "JWT_TOKEN_ISSUE",
  JWT_TIME_TO_LIVE: "JWT_TIME_TO_LIVE",
  JWT_REFRESH_TTL: "JWT_REFRESH_TTL",
};
